# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-27 03:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_breed_dog'),
    ]

    operations = [
        migrations.AddField(
            model_name='breed',
            name='size',
            field=models.CharField(choices=[('T', 'Tiny'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], default='M', max_length=32),
        ),
    ]
